### ISSUE TITLE
浏览器打开链接

### ISSUE THREAD

**Issue by Cqjn-zyk** [Ericwyn/electron-lark#11]
目前聊天记录有链接的话是又打开一个窗口，能否调用默认浏览器打开，或者chrome 打开呢

**Comment by Ericwyn** [comment]
当前的逻辑是如果 url 是飞书内部链接的话，就在窗口打开，否则使用浏览器打开

之前发现如果飞书内部有外链的话，链接之前会加`https://security.feishu.cn/link/safety?target=` 这样的前缀
所以当前就是以这个前缀来判断是否是外部链接，如果包含该前缀的话，去除前缀之后的链接会调用浏览器打开
否则会使用内部窗口打开

之所以这样做是为了在内部窗口打开文档/日历，避免了外部 chrome 打开时候还需要重新登录

你能提供以下你聊天记录当中的链接么？看看格式

**Comment by Cqjn-zyk** [comment]
http://gerrit.xxxxxxxcn/#/c/66666/  没有固定的链接，我希望都在chrome打开，你能告诉我在哪里改下吗

**Comment by Ericwyn** [comment]
https://github.com/Ericwyn/electron-lark/blob/f470033d9905b2e2d71ecb8c55f5818244f6b12e/src/main.js#L82-L111

修改成
```
            url = decodeURIComponent(url);
            shell.openExternal(url)
            return;
```

应该就可以了

**Comment by Cqjn-zyk** [comment]
可以了，多谢
