### ISSUE TITLE
CPU占用率100%

### ISSUE THREAD

**Issue by schspa** [Ericwyn/electron-lark#12]
如下图，cpu占用率经常到100%，然后点一下要5/6秒才有反应
![image](https://user-images.githubusercontent.com/3659289/107168157-ccdef580-69f5-11eb-9a9b-466065c503da.png)
系统信息截图
![image](https://user-images.githubusercontent.com/3659289/107168282-26472480-69f6-11eb-945a-eb52d9921d9b.png)

**Comment by schspa** [comment]
kill掉之后，重新启动可以恢复

**Comment by Ericwyn** [comment]
V1.1.1 版本已修复
