### ISSUE TITLE
打开链接能不能通过浏览器?

### ISSUE THREAD

**Issue by MarshallTeach007** [Ericwyn/electron-lark#16]

**Comment by atenjin** [comment]
+1 希望有一个这个功能。当前点击链接的时候看起来是直接用了一个webview打开了链接，有一些时候比较方便，但是有一些时候不方便：

* 打开共享文档的时候保留这样子挺好的
* 打开其他链接的时候希望能给一个跳转浏览器打开的选项，而不是靠复制

因为希望作者能否做一个类似微信的那种web界面的功能，首先可以在设置里面选择是否使用内置webview打开界面，然后用webview打开界面后，提供一个按钮，或者一个菜单栏按钮，点击在浏览器打开

**Comment by Ericwyn** [comment]
> +1 希望有一个这个功能。当前点击链接的时候看起来是直接用了一个webview打开了链接，有一些时候比较方便，但是有一些时候不方便：
> 
> * 打开共享文档的时候保留这样子挺好的
> * 打开其他链接的时候希望能给一个跳转浏览器打开的选项，而不是靠复制
> 
> 因为希望作者能否做一个类似微信的那种web界面的功能，首先可以在设置里面选择是否使用内置webview打开界面，然后用webview打开界面后，提供一个按钮，或者一个菜单栏按钮，点击在浏览器打开


确实是个好建议，有时间了我试试 :joy:

**Comment by Ericwyn** [comment]
最新版 Relese 1.1.0 已支持设置链接是否在浏览器中打开~
