### ISSUE TITLE
飞书 [话题] 消息对话框不能正常显示

### ISSUE THREAD

**Issue by taotieren** [Ericwyn/electron-lark#17]
electron-lark ![image](https://user-images.githubusercontent.com/13965460/117010651-94fafc00-ad1f-11eb-844e-be5c6837af23.png)

飞书 Windows 客户端 ![image](https://user-images.githubusercontent.com/13965460/117010750-ae9c4380-ad1f-11eb-86da-361f0d7a40cc.png)

**Comment by taotieren** [comment]
上次联系飞书客服，问过有没有支持 Linux 的计划，他们回复没有，看 Deeipin 论坛的管理员说的是有 Linux 原生计划，这个到底有没有呢？

**Comment by Ericwyn** [comment]
网页版飞书不支持显示话题聊天，你在网页版登录，看到的界面也会是这样，这是飞书网页版的问题~请向官方反馈~
