### ISSUE TITLE
富文本无法下拉滚动，且发送按钮被顶跑

### ISSUE THREAD

**Issue by zhang8473** [Ericwyn/electron-lark#18]
版本：electron-lark_1.1.1_amd64.deb

如果一次性复制粘贴大量文本，只能看见第一页，没办法查看编辑后面的内容

如图
![image](https://user-images.githubusercontent.com/5016962/117527644-214b3e80-b000-11eb-90e6-a80d6f93c281.png)

**Comment by Ericwyn** [comment]
请在浏览器网页版上面试试，如果网页版也有这个问题，那么是飞书官方的问题，请向飞书官方反馈
