### ISSUE TITLE
[请求] 为本项目添加合适的 License

### ISSUE THREAD

**Issue by whriedplanck** [Ericwyn/electron-lark#2]
阁下的项目完成度较高，我想将项目编译打包给 Arch Linux，但是阁下没有写明适用什么协议，给打包工作带来点困难。 MIT License 是个不错的选择，希望采纳。

**Comment by Ericwyn** [comment]
可以的啊～ 你有在 arch linux 下面尝试过么？ 我现在 ubuntu 18，锁屏之后再打开 tray 就会消失的这个问题一直无解来着

**Comment by whriedplanck** [comment]
> 可以的啊～ 你有在 arch linux 下面尝试过么？ 我现在 ubuntu 18，锁屏之后再打开 tray 就会消失的这个问题一直无解来着

尝试过了，可以用。不过我用的是 KDE，没有发现托盘 tray 的相关问题。

**Comment by NIL-zhuang** [comment]
## AUR仓库下载出错

请调整AUR仓库的链接

```txt
curl: (35) OpenSSL SSL_connect: 连接被对方重设 in connection to github-production-release-asset-2e65be.s3.amazonaws.com:443 
==> 错误： 无法下载 https://github.com/Ericwyn/electron-lark/releases/download/V1.0.1/electron-lark_1.0.1_amd64.deb
    正在放弃...
```

**Comment by Ericwyn** [comment]
@NIL-zhuang AUR 仓库并不是我这边在打包来着，看了一下打包的人似乎是 @whriedplanck 
你可以直接从 release 页面下载～

**Comment by whriedplanck** [comment]
> ## AUR仓库下载出错
> 
> 请调整AUR仓库的链接
> 
> ```
> curl: (35) OpenSSL SSL_connect: 连接被对方重设 in connection to github-production-release-asset-2e65be.s3.amazonaws.com:443 
> ==> 错误： 无法下载 https://github.com/Ericwyn/electron-lark/releases/download/V1.0.1/electron-lark_1.0.1_amd64.deb
>     正在放弃...
> ```

AUR 包的维护者是我，我的机器上测试链接是没问题的。您可能需要检查一下您的网络。
PS. 不过这提醒我该升级了。
@NIL-zhuang
