### ISSUE TITLE
图片无法下载

### ISSUE THREAD

**Issue by chriswongxp** [Ericwyn/electron-lark#21]
如果是其它格式的文件，像文本、压缩包、excel这些，都可以正常打开，但接收到的是png/jpeg这些图片的话，只能点击查看，无法下载，我都是打开开发者工具找到图片地址后，在浏览器下载的。

系统：archlinux
浏览器：firefox

**Comment by Ericwyn** [comment]
这个是飞书网页版限制噢~  只能是通过注入 js 之类的方法来给图片加一个下载按钮 ?

**Comment by Ericwyn** [comment]
最新 V1.1.6 版已解决
