### ISSUE TITLE
点击消息通知打开应用时跳转到具体的聊天窗口 - 在Ubuntu下无效

### ISSUE THREAD

**Issue by lanten** [Ericwyn/electron-lark#23]
版本 v1.1.2，根据 release 说明中的新增功能， 测试了一下点击消息后跳转，没有任何效果。

Ubuntu 20.04.2 LTS / GNOME

**Comment by Ericwyn** [comment]
注入的 js 有错误，前几天发现了，有时间了修一修

**Comment by Ericwyn** [comment]
Release 1.1.3 修复
