### ISSUE TITLE
（广告）飞书 Linux 原生版本

### ISSUE THREAD

**Issue by xobiwej413** [Ericwyn/electron-lark#24]
https://github.com/xobiwej413/lark-suite-linux/releases 飞书 Linux 原生版本。

**Comment by Ericwyn** [comment]
这个版本是从哪里来的啊~

**Comment by shoyuf** [comment]
> 这个版本是从哪里来的啊~

有点意思。。。内部人员拿源码打了一份 linux 版本的？安全性存疑

**Comment by oxoxoxox** [comment]
官方确实出了Linux版本，还在小范围公测中
https://bytedance.feishu.cn/docs/doccnT5wBv9Y9sgdccGsnTXe8nr

**Comment by Ericwyn** [comment]
> 官方确实出了Linux版本，还在小范围公测中
> https://bytedance.feishu.cn/docs/doccnT5wBv9Y9sgdccGsnTXe8nr

挺好的，我可以加到 README 里面，不过我们这边用的都是魔改版的飞书而不是官方的程序，所以现在也还是只能用网页版
