### ISSUE TITLE
飞书的后台运行后通过桌面启动器启动飞书会打开新的任务，而不是打开后台运行的任务

### ISSUE THREAD

**Issue by See-Night** [Ericwyn/electron-lark#26]
启动飞书后挂到后台运行，再启动的时候会无视后台运行的那个飞书，反而会新建一个飞书任务。
![image](https://user-images.githubusercontent.com/45226780/129482916-b3ab113a-b3d2-4a4a-996d-285f1330fe72.png)
![image](https://user-images.githubusercontent.com/45226780/129482925-e0a964b8-535e-489a-aac3-0aea54a53a03.png)

**Comment by Ericwyn** [comment]
这个应该算是 by-design, 类似于其他 electron 封装的工具都是这么个操作
暂时也没想到有啥好的方法
