### ISSUE TITLE
tray没有显示图标

### ISSUE THREAD

**Issue by willron** [Ericwyn/electron-lark#6]
Version: v1.0.2
OS：Linux Mint 19.3 Tricia
Desktop: Cinnamon

通知栏没有显示图标，但关闭窗口后alt+shift+m可以正常呼出界面

**Comment by willron** [comment]
用的是Appimage的包

**Comment by Ericwyn** [comment]
看起来是 electron tray 对各个系统支持的问题，你可以参考一下进行设置
https://github.com/electron/electron/issues/21445#issuecomment-565710027

**Comment by willron** [comment]
> 看起来是 electron tray 对各个系统支持的问题，你可以参考一下进行设置
> [electron/electron#21445 (comment)](https://github.com/electron/electron/issues/21445#issuecomment-565710027)

已经解决。需要打开首选项-常规-开启对指示器的支持。然后重启一下Cinnamon（Alt+F2, 输入r再回车）
