### ISSUE TITLE
希望能支持飞书的审批功能

### ISSUE THREAD

**Issue by chenyicai** [Ericwyn/electron-lark#9]
我的系统是deepin v2.0社区版，目前飞书的审批功能无法使用，未来随着头条的壮大，很多企业都会选飞书作为协同办公工具，如果咱们版本的飞书可以支持审批功能的话，那受益的用户会很感激你们的贡献的。

**Comment by Ericwyn** [comment]
你好~我只是封装了网页版的飞书而已，实际上就是个浏览器套壳，并不是官方开发人员噢，用户需求和功能开发请联系飞书官方人员吧~
